# Generated by Django 5.0.2 on 2024-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_autor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autor",
            old_name="descricao",
            new_name="nome",
        ),
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.URLField(blank=True, null=True),
        ),
    ]
